// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvxnczdntmpqdgyqzhjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2eG5jemRudG1wcWRneXF6aGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDc1NzYsImV4cCI6MjA2MTA4MzU3Nn0.onlGPBQqo7JbKiujmSgXVEECAKkVxCu4wOXpdsBwB28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);